plugins {
    id "com.android.application"
}

android {
    namespace "com.xiguang.app"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.xiguang.app"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    flavorDimensions "entry"
    productFlavors {
        desktop {
            dimension "entry"
            versionNameSuffix "-desktop"
        }
    }
}
